services:
    CleverAge\PermissionBundle\Form\Extension\FormPermissionExtension:
        autowire: true
        public: false
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    CleverAge\PermissionBundle\Voter\ClassVoter:
        autowire: true
        public: false
        tags:
            - { name: security.voter }

    CleverAge\PermissionBundle\Voter\DataVoter:
        autowire: true
        public: false
        tags:
            - { name: security.voter }
